[package]
name = "scrave-glyph-image-generator"
version = "0.1.0"
edition = "2024"
license.workspace = true
description.workspace = true
publish = false

[dependencies]
image.workspace = true

portal-solutions-scrave-glyph = { version = "0.1.0", path = "../scrave-glyph" }
